### PR TITLE
Astro testing and GitHub pages

### PR DESCRIPTION
**Pull request by omar-h-omar**
I've added 2 github actions. One for playwright tests and another for github pages. The playwright tests one will run on all astro branches. Playwright tests are end to end tests that test the workflow on a page. I've left an example of a test for index page. The github pages action only runs for the main astro branch. It would have to be updated in the `astro-navbar` branch to enable astro to grab the data from prisma probably just the env variable to link to the prod db.

### CODE REVIEW

**Comment by joe2k01** [comment]
Prod db isn't exposed. The credentials are public and the docker image does exposes the ports https://github.com/yorknouse/website/blob/master/docker-compose.yml#L24.

**Comment by omar-h-omar** [comment]
> Prod db isn't exposed. The credentials are public and the docker image does exposes the ports https://github.com/yorknouse/website/blob/master/docker-compose.yml#L24.
> 
> I don't think that should change, otherwise we'd have to change the credentials to the db. Expose the port and use a github secret. But I'd rather not have the db exposed for obv reasons.
> 
> I think we should probably just build locally and push to a pages branch

Hmm I see what you mean. It's just not ideal since we'd be pushing the dist build every time but I guess it's fine for now

**Comment by joe2k01** [comment]
> > Prod db isn't exposed. The credentials are public and the docker image does exposes the ports https://github.com/yorknouse/website/blob/master/docker-compose.yml#L24.
> 
> > 
> 
> > I don't think that should change, otherwise we'd have to change the credentials to the db. Expose the port and use a github secret. But I'd rather not have the db exposed for obv reasons.
> 
> > 
> 
> > I think we should probably just build locally and push to a pages branch
> 
> 
> 
> Hmm I see what you mean. It's just not ideal since we'd be pushing the dist build every time but I guess it's fine for now

I suppose we could set up a cron on the yusu vm to pull and update once a week/day/whatever, but I mean that's just more work than necessary imo

**Comment by omar-h-omar** [comment]
> > > Prod db isn't exposed. The credentials are public and the docker image does exposes the ports https://github.com/yorknouse/website/blob/master/docker-compose.yml#L24.
> > 
> > 
> > > 
> > 
> > 
> > > I don't think that should change, otherwise we'd have to change the credentials to the db. Expose the port and use a github secret. But I'd rather not have the db exposed for obv reasons.
> > 
> > 
> > > 
> > 
> > 
> > > I think we should probably just build locally and push to a pages branch
> > 
> > 
> > Hmm I see what you mean. It's just not ideal since we'd be pushing the dist build every time but I guess it's fine for now
> 
> I suppose we could set up a cron on the yusu vm to pull and update once a week/day/whatever, but I mean that's just more work than necessary imo

Nah that's too much tbh. this is just for them to view the progress anyway

**Review by joe2k01 — APPROVED** [review]

**Pull request merged**
