### PR TITLE
upgrading google sign on for the admin page

### PR DESCRIPTION
**Pull request by omar-h-omar**
I've updated the log in only for the admin side and not the comments. Google is planning on deprecating the old library from the end of march. Hopefully, we can have the new website up by then so no need to update the comments.

### CODE REVIEW

**Review by joe2k01 — APPROVED** [review]
I assume you mean the comments in coreHead.php. I guess those bits would stay the same, as the "common" code would then become just frontend code for the admin panel. If so, shouldn't we update them? Otherwise looks good

**Comment by omar-h-omar** [comment]
@joe2k01 no i was actually referring to the comments on the article pages. I did update the coreHead to include the new google urls

**Comment by omar-h-omar** [comment]
@joe2k01 if everything looks good to you. When you're free can you try it out on your end? Just wanna make everything is working as expected

**Comment by joe2k01** [comment]
> @joe2k01 if everything looks good to you. When you're free can you try it out on your end? Just wanna make everything is working as expected 

Yeah will do

**Pull request merged**
